# qltools
# Need to be root to do this !
INSTALL = install -s -g floppy -o root -m 02755
#INSTALL = cp

OBJS = qltools.o linux.o
CFLAGS = -O6 -I. -Wall

qltools : $(OBJS)
	$(CC)  -o qltools $(OBJS)
	strip qltools

linux.o : linux/linux.c 
	$(CC) -c $(CFLAGS) linux/linux.c

$(OBJS) : qltools.h

install: qltools
	$(INSTALL) qltools /usr/local/bin/

